### ISSUE TITLE
is_visible error since updating to newest version

### ISSUE THREAD

**Issue by AdamBD** [declancm/maximize.nvim#15]
E5108: Error executing lua ...im/lazy/maximize.nvim/lua/maximize/integrations/tree.lua:13: attempt to call field 'is_visible' (a nil value)
stack traceback:
	...im/lazy/maximize.nvim/lua/maximize/integrations/tree.lua:13: in function 'fn'
	...im/lazy/maximize.nvim/lua/maximize/integrations/init.lua:11: in function 'clear'
	...ocal/share/nvim/lazy/maximize.nvim/lua/maximize/init.lua:46: in function 'maximize'
	...ocal/share/nvim/lazy/maximize.nvim/lua/maximize/init.lua:24: in function 'toggle'
	[string ":lua"]:1: in main chunk

**Comment by declancm** [comment]
Do you have nvim-tree installed? What version are you using?
