### ISSUE TITLE
"Special" buffers are restored as empty buffers

### ISSUE THREAD

**Issue by RobertAudi** [declancm/maximize.nvim#2]
Special buffers like file tree buffers cannot be saved in the session so they are restored as empty buffers.

One solution to this problem can be to close these buffer like it's done in the [`neovim-session-manager`](https://github.com/Shatur/neovim-session-manager) plugin:

- https://github.com/Shatur/neovim-session-manager/blob/9652b392805dfd497877342e54c5a71be7907daf/lua/session_manager/utils.lua#L74-L79
- https://github.com/Shatur/neovim-session-manager/blob/9652b392805dfd497877342e54c5a71be7907daf/lua/session_manager/utils.lua#L129-L149

**Comment by declancm** [comment]
Thank you!
