### ISSUE TITLE
[Bug] Toggle, Toggle, Toggle Sequence gives "Already one window" error

### ISSUE THREAD

**Issue by ElPiloto** [declancm/maximize.nvim#4]
**System Information:**
I'm on neovim 0.7.2.

**How to reproduce and issue:**
Open up a second buffer in a vertical split, so that we have two files, let's call them "buffer1" and "buffer2" in the left and right splits respectively.  Then with focus on buffer1, run `:lua require('maximize').toggle()` three times (once to maximize,then minimize, then maximize again).   On the third toggle, I get a message that says `Already only one window` and the split with buffer1 is closed and only buffer2 is visible.  Subsequent toggle calls don't do anything.

**Comment by kulubaev** [comment]
i got same issue, any updates

**Comment by KostkaBrukowa** [comment]
It seems that the "parent" plugin (https://github.com/declancm/windex.nvim) does not have this error and it works well there

**Comment by declancm** [comment]
Hi! Sorry I didn't get to this earlier, I have been busy with a new job. I just pushed a fix. Please let me know if it's working for you!
